### ISSUE TITLE
Add to Android Play Store

### ISSUE THREAD

**Issue by ghedsouza** [kaie/otp-authenticator-android#2]
Would it possible to add the official binary for this app to the Play Store?

**Comment by kaie** [comment]
May I recommend that you use the FreeOTP app instead, which is available in the Play Store? In my understanding, it is equivalent, and open source, too. See https://fedorahosted.org/freeotp/

**Comment by ghedsouza** [comment]
@kale Ok. I only requested this as a convenience.
